const client=window.kaabeSupabase,$=s=>document.querySelector(s);
const id=new URLSearchParams(location.search).get("id");let agent=null;
function note(){const m=$("#reply-mode").value;$("#mode-note").textContent=m==="auto_reply"?"Auto Reply: the assistant can send replies automatically.":m==="approval_required"?"Approval Required: Kaabe prepares the reply, but a person approves it before sending.":"Draft Only: Kaabe creates drafts and never sends them automatically."}
function pill(){const a=$("#agent-status").value==="active";$("#status-pill").textContent=a?"● Active":"● Paused";$("#status-pill").className="status-pill "+(a?"active":"")}
(async()=>{const{data:s,error:se}=await client.auth.getSession();if(se||!s.session){location.href="login.html";return}if(!id){location.href="assistants.html";return}
const{data,error}=await client.from("agents").select("*").eq("id",id).single();if(error||!data){alert("Assistant not found or you do not have access.");location.href="assistants.html";return}
agent=data;const st=agent.settings||{};$("#agent-name").value=agent.name||"";$("#agent-type").value=agent.type||"";$("#agent-instructions").value=st.instructions||"";$("#agent-tone").value=st.tone||"professional";$("#reply-mode").value=st.reply_mode||"approval_required";$("#agent-status").value=agent.status||"paused";$("#loading").hidden=true;$("#agent-form").hidden=false;note();pill()})();
$("#reply-mode").addEventListener("change",note);$("#agent-status").addEventListener("change",pill);
$("#agent-form").addEventListener("submit",async e=>{e.preventDefault();const b=$("#save-btn");b.disabled=true;b.textContent="Saving…";$("#save-state").textContent="";const settings={...(agent.settings||{}),instructions:$("#agent-instructions").value.trim(),tone:$("#agent-tone").value,reply_mode:$("#reply-mode").value};const payload={name:$("#agent-name").value.trim(),status:$("#agent-status").value,settings,updated_at:new Date().toISOString()};const{data,error}=await client.from("agents").update(payload).eq("id",id).select().single();b.disabled=false;b.textContent="Save Changes";if(error){$("#save-state").textContent="Error: "+error.message;return}agent=data;$("#save-state").textContent="✓ Changes saved to Kaabe";pill()});
$("#delete-agent").addEventListener("click",async()=>{if(!confirm("Delete this AI assistant permanently?"))return;const b=$("#delete-agent");b.disabled=true;b.textContent="Deleting…";const{error}=await client.from("agents").delete().eq("id",id);if(error){b.disabled=false;b.textContent="Delete Assistant";alert(error.message);return}location.href="assistants.html"});