const client=window.kaabeSupabase,$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let business=null,items=[];
const labels={business_info:"Business Info",opening_hours:"Opening Hours",services:"Services",prices:"Prices",faq:"FAQ",policy:"Policies",other:"Other"};
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){ $("#knowledge-count").textContent=items.length;const g=$("#knowledge-grid");if(!items.length){g.innerHTML='<div class="empty"><h3>No knowledge yet</h3><p>Add your business information, hours, services, prices, FAQs and policies.</p></div>';return}g.innerHTML=items.map(x=>`<article class="kb-item" data-id="${x.id}"><span class="cat">${esc(labels[x.category]||x.category)}</span><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></article>`).join("");$$(".kb-item").forEach(x=>x.onclick=()=>openEdit(x.dataset.id))}
async function load(){const{data,error}=await client.from("knowledge_items").select("*").eq("business_id",business.id).order("updated_at",{ascending:false});if(error){alert("Knowledge error: "+error.message);return}items=data||[];render()}
function openNew(){$("#kb-form").reset();$("#item-id").value="";$("#modal-title").textContent="Add Knowledge";$("#delete-item").classList.add("hidden");$("#kb-state").textContent="";$("#kb-modal").classList.add("open")}
function openEdit(id){const x=items.find(v=>v.id===id);if(!x)return;$("#item-id").value=x.id;$("#item-category").value=x.category;$("#item-title").value=x.title;$("#item-content").value=x.content;$("#modal-title").textContent="Edit Knowledge";$("#delete-item").classList.remove("hidden");$("#kb-state").textContent="";$("#kb-modal").classList.add("open")}
function closeModal(){$("#kb-modal").classList.remove("open")}
(async()=>{const{data:s}=await client.auth.getSession();if(!s.session){location.href="login.html";return}const u=s.session.user,n=u.user_metadata?.full_name||u.email?.split("@")[0]||"User";$("#account-name").textContent=n;$("#avatar").textContent=n[0].toUpperCase();const{data:b}=await client.from("businesses").select("id,name,timezone").eq("owner_id",u.id).order("created_at",{ascending:true}).limit(1);if(!b?.length){location.href="onboarding.html";return}business=b[0];$("#side-business").textContent=business.name;$("#side-zone").textContent=business.timezone||"Europe/Berlin";await load()})();
$("#add-item").onclick=openNew;$("#kb-close").onclick=closeModal;$("#kb-modal").onclick=e=>{if(e.target.id==="kb-modal")closeModal()};
$("#kb-form").onsubmit=async e=>{e.preventDefault();const btn=$("#save-item");btn.disabled=true;btn.textContent="Saving…";const id=$("#item-id").value,payload={business_id:business.id,category:$("#item-category").value,title:$("#item-title").value.trim(),content:$("#item-content").value.trim(),updated_at:new Date().toISOString()};let r=id?await client.from("knowledge_items").update(payload).eq("id",id).select().single():await client.from("knowledge_items").insert(payload).select().single();btn.disabled=false;btn.textContent="Save Knowledge";if(r.error){$("#kb-state").textContent="Error: "+r.error.message;return}await load();closeModal()};
$("#delete-item").onclick=async()=>{const id=$("#item-id").value;if(!id||!confirm("Delete this knowledge item?"))return;const{error}=await client.from("knowledge_items").delete().eq("id",id);if(error){alert(error.message);return}await load();closeModal()};
$("#menu-btn")?.addEventListener("click",()=>{$("#sidebar")?.classList.toggle("open");$("#sidebar-backdrop")?.classList.toggle("open")});$("#sidebar-close")?.addEventListener("click",()=>{$("#sidebar")?.classList.remove("open");$("#sidebar-backdrop")?.classList.remove("open")});$("#sidebar-backdrop")?.addEventListener("click",()=>{$("#sidebar")?.classList.remove("open");$("#sidebar-backdrop")?.classList.remove("open")});