(()=>{const css=document.createElement('style');css.textContent=`
#kaabe-chat-launch{position:fixed;right:22px;bottom:22px;z-index:9998;border:0;border-radius:999px;padding:15px 20px;background:linear-gradient(110deg,#087bff,#7439ee);color:white;font-weight:700;box-shadow:0 12px 30px #12234b55;cursor:pointer}
#kaabe-public-chat{position:fixed;right:22px;bottom:82px;z-index:9999;width:min(380px,calc(100vw - 28px));height:min(530px,calc(100dvh - 110px));background:#091a31;color:#f3f7ff;border:1px solid #314765;border-radius:18px;box-shadow:0 18px 50px #08132666;display:none;flex-direction:column;overflow:hidden;font-family:system-ui,sans-serif}
#kaabe-public-chat.open{display:flex}#kaabe-public-chat header{position:static;display:flex;align-items:center;justify-content:space-between;background:#102743;padding:16px;border:0;min-height:auto}#kaabe-public-chat header button{background:transparent;border:0;color:white;font-size:23px;cursor:pointer}
#kaabe-public-messages{flex:1;overflow-y:auto;padding:15px;display:flex;flex-direction:column;gap:12px}#kaabe-public-messages .msg{max-width:88%;padding:11px 13px;border-radius:13px;line-height:1.5;font-size:14px;white-space:pre-wrap}#kaabe-public-messages .bot{background:#17304f;align-self:flex-start}#kaabe-public-messages .user{background:#175fda;align-self:flex-end}
#kaabe-public-chat form{display:flex;gap:8px;padding:12px;background:#102743}#kaabe-public-chat input{flex:1;min-width:0;background:#07182e;border:1px solid #355170;color:#fff;padding:12px;border-radius:10px}#kaabe-public-chat form button{border:0;background:#2778ee;color:white;padding:10px 13px;border-radius:10px;cursor:pointer}
#kaabe-public-chat .note{font-size:11px;color:#a4bad5;padding:0 12px 10px;background:#102743}
`;document.head.append(css);
const launch=document.createElement('button');launch.id='kaabe-chat-launch';launch.textContent='✦ Ask KAABE AI';launch.setAttribute('aria-label','Open KAABE assistant');
const panel=document.createElement('section');panel.id='kaabe-public-chat';panel.setAttribute('aria-label','KAABE assistant');panel.innerHTML='<header><strong>✦ KAABE AI Assistant</strong><button type="button" aria-label="Close chat">×</button></header><div id="kaabe-public-messages" role="log" aria-live="polite"></div><form><input aria-label="Your question" placeholder="Ask about KAABE..." maxlength="500" required><button type="submit">Send</button></form><div class="note">Website information assistant · AI chat connection coming soon</div>';document.body.append(launch,panel);
const messages=panel.querySelector('#kaabe-public-messages');function add(text,who){const e=document.createElement('div');e.className='msg '+who;e.textContent=text;messages.append(e);messages.scrollTop=messages.scrollHeight}
add('Welcome to KAABE! Ask me about our services, pricing, or how to get started.','bot');
launch.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))panel.querySelector('input').focus()};panel.querySelector('header button').onclick=()=>panel.classList.remove('open');
function answer(q){const x=q.toLowerCase();if(/price|pricing|cost|qiim|lacag|preis|kosten|€/.test(x))return 'KAABE website lists Starter €29/month, Professional €59/month, and Business €99/month. See the Pricing section for plan details.';if(/whatsapp|email|gmail|booking|appointment|ballan|autom|service|adeeg|funktion/.test(x))return 'KAABE is being built to help businesses automate WhatsApp, email, bookings, and customer support. Integrations may still be under development.';if(/start|sign|account|bilaab|registr|anmeld/.test(x))return 'To get started, select Get Started on this website and create your KAABE account.';if(/somali|soomaali|af somali/.test(x))return 'Haa, waan ku caawin karaa xogta KAABE. Waxaad i weydiin kartaa adeegyada, qiimaha, iyo sida akoon loo sameeyo.';return 'I can currently answer common questions about KAABE services, pricing, and signup. Full AI-powered public chat is not connected yet. What would you like to know?'}
panel.querySelector('form').onsubmit=e=>{e.preventDefault();const input=panel.querySelector('input');const q=input.value.trim();if(!q)return;input.value='';add(q,'user');add(answer(q),'bot')};
})();